# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # This makes it possible to run the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: postgres
      APP_DB_NAME: postgres
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Start postgres container
      run: docker run -p 5432:5432 -e POSTGRES_PASSWORD=${{ env.APP_DB_PASSWORD }} -e POSTGRES_USER=${{ env.APP_DB_USERNAME }} -e POSTGRES_DB=${{ env.APP_DB_NAME }} -d postgres

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
        
    - name: Get
      run: go get -v

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
