name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # This makes it possible to run the workflow manually

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env: 
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: postgres
      APP_DB_NAME: postgres
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Start postgres container
      run: docker run -p 5432:5432 -e POSTGRES_PASSWORD=${{ env.APP_DB_PASSWORD }} -e POSTGRES_USER=${{ env.APP_DB_USERNAME }} -e POSTGRES_DB=${{ env.APP_DB_NAME }} -d postgres

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.0
        
    - name: Get
      run: go get -v

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -coverprofile=coverage.out ./... 
  
  sonarAnalyze:
    needs: build
    name: Analyze Code
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - uses: sonarsource/sonarcloud-github-action@v1.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
